### ISSUE TITLE
torch 2.3.1 is not supported?

### ISSUE THREAD

**Issue by George0828Zhang** [JonasGeiping/linear_cross_entropy_loss#1]
Using torch==2.3.1 gives import error:
```
AttributeError: module 'torch.amp' has no attribute 'custom_fwd'
```
I think the naming changed between 2.3 and 2.4. 

However, even if you changed them to the following:
```
# @torch.amp.custom_fwd(device_type="cuda", cast_inputs=torch.float16)
@torch.cuda.amp.custom_fwd(cast_inputs=torch.float16)

# @torch.amp.custom_bwd(device_type="cuda")
@torch.cuda.amp.custom_bwd
```
the import error is gone but still you'll get:
```
TypeError: 'staticmethod' object is not callable
```

**Comment by JonasGeiping** [comment]
Hi! I'm only using this implementation with torch 2.5 (nightly), but this should be a fixable problem. Can you remove all decorators aside from `staticmethod` from the custom autograd function?

**Comment by George0828Zhang** [comment]
Hi, thanks for replying,
While this does fix the type error, I'm now getting triton compilation error:
```
triton.compiler.errors.CompilationError: at 67:12:            ignore_index,
            idx_N_group,
            N_group,
            V,
            N,
            H,
            V_BLOCK_SIZE,
            N_BLOCK_SIZE,
            H_BLOCK_SIZE,
            GROUP_SIZE,
            SPLIT_N,
            SPLIT_V,
            ^
AttributeError("'int' object has no attribute 'value'")
```
Any tips on how to debug triton? mgmalek's version was working fine for me but I wanted to upgrade to this one

**Comment by JonasGeiping** [comment]
This looks like a problem with your triton version. I've rebuilt  a `2.3.1` env of my own, and I cannot reproduce this error, using triton 3.0.0.

If you have torch `2.3.1` installed, you might be runnning `torchtriton-2.3.0` by default. Updating to `triton-3.0.0` should work out of the box without breaking anything.

**Comment by JonasGeiping** [comment]
Hope this helps!
